/*

 MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 60 x 16
   Tile set      : D:\GB_game_projects\EC2020\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundMap1Width 60
#define backgroundMap1Height 16
#define backgroundMap1Bank 0

extern unsigned char backgroundMap1[];

/* End of MAP1.H */
