/*

 MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 60 x 16
   Tile set      : D:\GB_game_projects\EC2020\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundMap2Width 60
#define backgroundMap2Height 16
#define backgroundMap2Bank 0

extern unsigned char backgroundMap2[];

/* End of MAP2.H */
