/*

 MAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 60 x 17
   Tile set      : D:\GB_game_projects\EC2020\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMap3Width 60
#define BackgroundMap3Height 17
#define BackgroundMap3Bank 0

extern unsigned char BackgroundMap3[];

/* End of MAP3.H */
